import { writeFileSync } from "node:fs";
import path from "node:path";
import { collectRun } from "../lib/agent/harness";
import { GOAL_CHIPS } from "../lib/agent/scenarios";
import { PRESET_WEIGHTS } from "../lib/routing/weights";
import { defaultPolicy } from "../lib/wallet/policy";

/** Records deterministic runs (testClock) as typed TS data for the landing replays. */
async function record(file: string, exportName: string, goal: string, preset: "accuracy" | "balanced", budgetMicro: number) {
  const { events } = await collectRun(goal, {
    budgetMicro,
    preset,
    weights: PRESET_WEIGHTS[preset],
    policy: defaultPolicy(),
  });
  const out = path.join(import.meta.dirname, "..", "lib", "agent", "recorded", file);
  const src =
    `// GENERATED by scripts/record-runs.ts — do not edit. Simulated run recorded with a deterministic test clock.\n` +
    `import type { RunEvent } from "../events";\n\n` +
    `export const ${exportName}: RunEvent[] = ${JSON.stringify(events)};\n`;
  writeFileSync(out, src);
  console.log(`${exportName}: ${events.length} events → ${out} (${Math.round(src.length / 1024)} KB)`);
}

async function main() {
  await record("vision.ts", "RECORDED_VISION_RUN", GOAL_CHIPS[0].goal, "accuracy", 100_000);
  await record("research.ts", "RECORDED_RESEARCH_RUN", GOAL_CHIPS[1].goal, "balanced", 100_000);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
