"use client";

import { useEffect, useRef } from "react";
import type { DuoScene } from "./scene/DuoScene";

/** Lazy three.js turntable. Renders only while on screen; drag (or swipe) to spin. */
export function DuoCanvas({ modelUrl, className }: { modelUrl: string; className?: string }) {
  const ref = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    let scene: DuoScene | null = null;
    let raf = 0;
    let visible = false;
    let disposed = false;
    let angle = 0.5;
    let dragging = false;
    let lastX = 0;
    let last = performance.now();

    const loop = (now: number) => {
      const dt = Math.min(0.05, (now - last) / 1000);
      last = now;
      if (!dragging && !reduced) angle += dt * 0.5;
      scene?.render(angle);
      if (visible && !reduced) raf = requestAnimationFrame(loop);
    };
    const kick = () => {
      cancelAnimationFrame(raf);
      last = performance.now();
      raf = requestAnimationFrame(loop);
    };
    const resize = () => {
      scene?.resize(canvas.clientWidth, canvas.clientHeight);
      kick();
    };
    const down = (e: PointerEvent) => {
      dragging = true;
      lastX = e.clientX;
      canvas.setPointerCapture(e.pointerId);
    };
    const move = (e: PointerEvent) => {
      if (!dragging) return;
      angle += (e.clientX - lastX) * 0.012;
      lastX = e.clientX;
      if (reduced) kick();
    };
    const up = () => {
      dragging = false;
    };

    const io = new IntersectionObserver(([e]) => {
      visible = e.isIntersecting;
      if (visible && !scene && !disposed) {
        import("./scene/DuoScene").then(({ DuoScene }) => {
          if (disposed || scene) return;
          scene = new DuoScene(canvas, modelUrl, window.innerWidth < 768);
          resize();
          // the model loads async; repaint a few times for reduced-motion users
          if (reduced) [400, 1200, 2500].forEach((ms) => setTimeout(kick, ms));
        });
      } else if (visible) kick();
    }, { rootMargin: "200px" });
    io.observe(canvas);
    const ro = new ResizeObserver(resize);
    ro.observe(canvas);
    canvas.addEventListener("pointerdown", down);
    canvas.addEventListener("pointermove", move);
    canvas.addEventListener("pointerup", up);
    canvas.addEventListener("pointercancel", up);

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
      io.disconnect();
      ro.disconnect();
      canvas.removeEventListener("pointerdown", down);
      canvas.removeEventListener("pointermove", move);
      canvas.removeEventListener("pointerup", up);
      canvas.removeEventListener("pointercancel", up);
      scene?.dispose();
    };
  }, [modelUrl]);

  return <canvas ref={ref} className={className} role="img" aria-label="Two robots on a turntable: left written as code by Claude, right generated by a 3D API. Drag to rotate." style={{ touchAction: "pan-y", cursor: "grab" }} />;
}
